dist: bionic
services:
  - xvfb
language: ruby
rvm:
  - 2.7
  - 2.6
  - 2.5
before_install:
  - export GR_VERSION=0.52.0
  - chmod +x ./test/ci/install_gr.sh
  - ./test/ci/install_gr.sh
  - export GRDIR=$HOME/GR/$GR_VERSION/gr
# Remove this item when a new version of Fiddle is released 
# that supports the variadic function
install:
  - gem install specific_install
  - gem specific_install https://github.com/ruby/fiddle
  - bundle update
cache:
  bundler: true
  directories:
    - $HOME/GR
script: bundle exec rake test
